[package]
name = "class-type"
version = "0.10.0"
edition = "2018"

[dependencies]
ckb-std = "0.7.1"
script-utils = { path = "../script-utils" }
nft-smt = {path = "../../nft-smt", default_features = false, features = ["no-std"]}