version = "0.7.2"
deployment = "deployment.toml"
[rust]
workspace_dir = "contracts"
toolchain = "nightly-2021-08-16"

[[contracts]]
name = "issuer-type"
template_type = "Rust"

[[contracts]]
name = "class-type"
template_type = "Rust"

[[contracts]]
name = "nft-type"
template_type = "Rust"
