version = "0.6.0 b850e01"
deployment = "deployment.toml"

[rust]
workspace_dir = "."
toolchain = "nightly-2021-08-16"
docker_image = "thewawar/ckb-capsule:2021-08-16"

[[contracts]]
name = "issuer-type"
template_type = "Rust"

[[contracts]]
name = "class-type"
template_type = "Rust"

[[contracts]]
name = "nft-type"
template_type = "Rust"

[[contracts]]
name = "compact-registry-type"
template_type = "Rust"

[[contracts]]
name = "compact-nft-type"
template_type = "Rust"