version = "0.4.3 13d6f1d"
deployment = "deployment.toml"
[rust]
workspace_dir = "contracts"
toolchain = "nightly-2020-09-28"

[[contracts]]
name = "issuer-type"
template_type = "Rust"

[[contracts]]
name = "class-type"
template_type = "Rust"

[[contracts]]
name = "nft-type"
template_type = "Rust"

[[contracts]]
name = "compact-registry-type"
template_type = "Rust"

[[contracts]]
name = "compact-nft-type"
template_type = "Rust"