[workspace]
members = ["contracts/issuer-type", "contracts/class-type", "contracts/nft-type", "contracts/script-utils", "tests"]

[profile.release]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
