 [[cells]]
 # name = "issuer-type / nft-type"
 name = "class-type"
 enable_type_id = true
 # location = { file = "build/release/issuer-type" }
 # location = { file = "build/release/nft-type" }
 location = { file = "build/release/class-type" }

 [lock]
 code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
 args = "0x0"
 hash_type = "type"

