// Generated by Molecule 0.7.0
#![allow(unused_imports)]
#![allow(dead_code)]
#![allow(clippy::if_same_then_else)]

use super::ckb_types::{packed::*, prelude::*};
use super::molecule::{self, prelude::*};
use super::common::*;
extern crate alloc;
pub use alloc::vec::*;
// these lines above are manually added
// replace "molecule" to "molecule" in below code

#[derive(Clone)]
pub struct CompactNFTId(molecule::bytes::Bytes);
impl ::core::fmt::LowerHex for CompactNFTId {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl ::core::fmt::Debug for CompactNFTId {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl ::core::fmt::Display for CompactNFTId {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(f, "{}: {}", "smt_type", self.smt_type())?;
        write!(f, ", {}: {}", "issuer_id", self.issuer_id())?;
        write!(f, ", {}: {}", "class_id", self.class_id())?;
        write!(f, ", {}: {}", "token_id", self.token_id())?;
        write!(f, " }}")
    }
}
impl ::core::default::Default for CompactNFTId {
    fn default() -> Self {
        let v: Vec<u8> = vec![
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        ];
        CompactNFTId::new_unchecked(v.into())
    }
}
impl CompactNFTId {
    pub const FIELD_COUNT: usize = 4;
    pub const FIELD_SIZES: [usize; 4] = [1, 20, 4, 4];
    pub const TOTAL_SIZE: usize = 29;

    pub fn smt_type(&self) -> Byte {
        Byte::new_unchecked(self.0.slice(0..1))
    }

    pub fn issuer_id(&self) -> IssuerId {
        IssuerId::new_unchecked(self.0.slice(1..21))
    }

    pub fn class_id(&self) -> Uint32 {
        Uint32::new_unchecked(self.0.slice(21..25))
    }

    pub fn token_id(&self) -> Uint32 {
        Uint32::new_unchecked(self.0.slice(25..29))
    }

    pub fn as_reader<'r>(&'r self) -> CompactNFTIdReader<'r> {
        CompactNFTIdReader::new_unchecked(self.as_slice())
    }
}
impl molecule::prelude::Entity for CompactNFTId {
    type Builder = CompactNFTIdBuilder;

    const NAME: &'static str = "CompactNFTId";

    fn new_unchecked(data: molecule::bytes::Bytes) -> Self {
        CompactNFTId(data)
    }

    fn as_bytes(&self) -> molecule::bytes::Bytes {
        self.0.clone()
    }

    fn as_slice(&self) -> &[u8] {
        &self.0[..]
    }

    fn from_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        CompactNFTIdReader::from_slice(slice).map(|reader| reader.to_entity())
    }

    fn from_compatible_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        CompactNFTIdReader::from_compatible_slice(slice).map(|reader| reader.to_entity())
    }

    fn new_builder() -> Self::Builder {
        ::core::default::Default::default()
    }

    fn as_builder(self) -> Self::Builder {
        Self::new_builder()
            .smt_type(self.smt_type())
            .issuer_id(self.issuer_id())
            .class_id(self.class_id())
            .token_id(self.token_id())
    }
}
#[derive(Clone, Copy)]
pub struct CompactNFTIdReader<'r>(&'r [u8]);
impl<'r> ::core::fmt::LowerHex for CompactNFTIdReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl<'r> ::core::fmt::Debug for CompactNFTIdReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl<'r> ::core::fmt::Display for CompactNFTIdReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(f, "{}: {}", "smt_type", self.smt_type())?;
        write!(f, ", {}: {}", "issuer_id", self.issuer_id())?;
        write!(f, ", {}: {}", "class_id", self.class_id())?;
        write!(f, ", {}: {}", "token_id", self.token_id())?;
        write!(f, " }}")
    }
}
impl<'r> CompactNFTIdReader<'r> {
    pub const FIELD_COUNT: usize = 4;
    pub const FIELD_SIZES: [usize; 4] = [1, 20, 4, 4];
    pub const TOTAL_SIZE: usize = 29;

    pub fn smt_type(&self) -> ByteReader<'r> {
        ByteReader::new_unchecked(&self.as_slice()[0..1])
    }

    pub fn issuer_id(&self) -> IssuerIdReader<'r> {
        IssuerIdReader::new_unchecked(&self.as_slice()[1..21])
    }

    pub fn class_id(&self) -> Uint32Reader<'r> {
        Uint32Reader::new_unchecked(&self.as_slice()[21..25])
    }

    pub fn token_id(&self) -> Uint32Reader<'r> {
        Uint32Reader::new_unchecked(&self.as_slice()[25..29])
    }
}
impl<'r> molecule::prelude::Reader<'r> for CompactNFTIdReader<'r> {
    type Entity = CompactNFTId;

    const NAME: &'static str = "CompactNFTIdReader";

    fn to_entity(&self) -> Self::Entity {
        Self::Entity::new_unchecked(self.as_slice().to_owned().into())
    }

    fn new_unchecked(slice: &'r [u8]) -> Self {
        CompactNFTIdReader(slice)
    }

    fn as_slice(&self) -> &'r [u8] {
        self.0
    }

    fn verify(slice: &[u8], _compatible: bool) -> molecule::error::VerificationResult<()> {
        use molecule::verification_error as ve;
        let slice_len = slice.len();
        if slice_len != Self::TOTAL_SIZE {
            return ve!(Self, TotalSizeNotMatch, Self::TOTAL_SIZE, slice_len);
        }
        Ok(())
    }
}
#[derive(Debug, Default)]
pub struct CompactNFTIdBuilder {
    pub(crate) smt_type:  Byte,
    pub(crate) issuer_id: IssuerId,
    pub(crate) class_id:  Uint32,
    pub(crate) token_id:  Uint32,
}
impl CompactNFTIdBuilder {
    pub const FIELD_COUNT: usize = 4;
    pub const FIELD_SIZES: [usize; 4] = [1, 20, 4, 4];
    pub const TOTAL_SIZE: usize = 29;

    pub fn smt_type(mut self, v: Byte) -> Self {
        self.smt_type = v;
        self
    }

    pub fn issuer_id(mut self, v: IssuerId) -> Self {
        self.issuer_id = v;
        self
    }

    pub fn class_id(mut self, v: Uint32) -> Self {
        self.class_id = v;
        self
    }

    pub fn token_id(mut self, v: Uint32) -> Self {
        self.token_id = v;
        self
    }
}
impl molecule::prelude::Builder for CompactNFTIdBuilder {
    type Entity = CompactNFTId;

    const NAME: &'static str = "CompactNFTIdBuilder";

    fn expected_length(&self) -> usize {
        Self::TOTAL_SIZE
    }

    fn write<W: molecule::io::Write>(&self, writer: &mut W) -> molecule::io::Result<()> {
        writer.write_all(self.smt_type.as_slice())?;
        writer.write_all(self.issuer_id.as_slice())?;
        writer.write_all(self.class_id.as_slice())?;
        writer.write_all(self.token_id.as_slice())?;
        Ok(())
    }

    fn build(&self) -> Self::Entity {
        let mut inner = Vec::with_capacity(self.expected_length());
        self.write(&mut inner)
            .unwrap_or_else(|_| panic!("{} build should be ok", Self::NAME));
        CompactNFTId::new_unchecked(inner.into())
    }
}
#[derive(Clone)]
pub struct CompactNFTIdVec(molecule::bytes::Bytes);
impl ::core::fmt::LowerHex for CompactNFTIdVec {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl ::core::fmt::Debug for CompactNFTIdVec {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl ::core::fmt::Display for CompactNFTIdVec {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} [", Self::NAME)?;
        for i in 0..self.len() {
            if i == 0 {
                write!(f, "{}", self.get_unchecked(i))?;
            } else {
                write!(f, ", {}", self.get_unchecked(i))?;
            }
        }
        write!(f, "]")
    }
}
impl ::core::default::Default for CompactNFTIdVec {
    fn default() -> Self {
        let v: Vec<u8> = vec![0, 0, 0, 0];
        CompactNFTIdVec::new_unchecked(v.into())
    }
}
impl CompactNFTIdVec {
    pub const ITEM_SIZE: usize = 29;

    pub fn total_size(&self) -> usize {
        molecule::NUMBER_SIZE * (self.item_count() + 1)
    }

    pub fn item_count(&self) -> usize {
        molecule::unpack_number(self.as_slice()) as usize
    }

    pub fn len(&self) -> usize {
        self.item_count()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    pub fn get(&self, idx: usize) -> Option<CompactNFTId> {
        if idx >= self.len() {
            None
        } else {
            Some(self.get_unchecked(idx))
        }
    }

    pub fn get_unchecked(&self, idx: usize) -> CompactNFTId {
        let start = molecule::NUMBER_SIZE + Self::ITEM_SIZE * idx;
        let end = start + Self::ITEM_SIZE;
        CompactNFTId::new_unchecked(self.0.slice(start..end))
    }

    pub fn as_reader<'r>(&'r self) -> CompactNFTIdVecReader<'r> {
        CompactNFTIdVecReader::new_unchecked(self.as_slice())
    }
}
impl molecule::prelude::Entity for CompactNFTIdVec {
    type Builder = CompactNFTIdVecBuilder;

    const NAME: &'static str = "CompactNFTIdVec";

    fn new_unchecked(data: molecule::bytes::Bytes) -> Self {
        CompactNFTIdVec(data)
    }

    fn as_bytes(&self) -> molecule::bytes::Bytes {
        self.0.clone()
    }

    fn as_slice(&self) -> &[u8] {
        &self.0[..]
    }

    fn from_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        CompactNFTIdVecReader::from_slice(slice).map(|reader| reader.to_entity())
    }

    fn from_compatible_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        CompactNFTIdVecReader::from_compatible_slice(slice).map(|reader| reader.to_entity())
    }

    fn new_builder() -> Self::Builder {
        ::core::default::Default::default()
    }

    fn as_builder(self) -> Self::Builder {
        Self::new_builder().extend(self.into_iter())
    }
}
#[derive(Clone, Copy)]
pub struct CompactNFTIdVecReader<'r>(&'r [u8]);
impl<'r> ::core::fmt::LowerHex for CompactNFTIdVecReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl<'r> ::core::fmt::Debug for CompactNFTIdVecReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl<'r> ::core::fmt::Display for CompactNFTIdVecReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} [", Self::NAME)?;
        for i in 0..self.len() {
            if i == 0 {
                write!(f, "{}", self.get_unchecked(i))?;
            } else {
                write!(f, ", {}", self.get_unchecked(i))?;
            }
        }
        write!(f, "]")
    }
}
impl<'r> CompactNFTIdVecReader<'r> {
    pub const ITEM_SIZE: usize = 29;

    pub fn total_size(&self) -> usize {
        molecule::NUMBER_SIZE * (self.item_count() + 1)
    }

    pub fn item_count(&self) -> usize {
        molecule::unpack_number(self.as_slice()) as usize
    }

    pub fn len(&self) -> usize {
        self.item_count()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    pub fn get(&self, idx: usize) -> Option<CompactNFTIdReader<'r>> {
        if idx >= self.len() {
            None
        } else {
            Some(self.get_unchecked(idx))
        }
    }

    pub fn get_unchecked(&self, idx: usize) -> CompactNFTIdReader<'r> {
        let start = molecule::NUMBER_SIZE + Self::ITEM_SIZE * idx;
        let end = start + Self::ITEM_SIZE;
        CompactNFTIdReader::new_unchecked(&self.as_slice()[start..end])
    }
}
impl<'r> molecule::prelude::Reader<'r> for CompactNFTIdVecReader<'r> {
    type Entity = CompactNFTIdVec;

    const NAME: &'static str = "CompactNFTIdVecReader";

    fn to_entity(&self) -> Self::Entity {
        Self::Entity::new_unchecked(self.as_slice().to_owned().into())
    }

    fn new_unchecked(slice: &'r [u8]) -> Self {
        CompactNFTIdVecReader(slice)
    }

    fn as_slice(&self) -> &'r [u8] {
        self.0
    }

    fn verify(slice: &[u8], _compatible: bool) -> molecule::error::VerificationResult<()> {
        use molecule::verification_error as ve;
        let slice_len = slice.len();
        if slice_len < molecule::NUMBER_SIZE {
            return ve!(Self, HeaderIsBroken, molecule::NUMBER_SIZE, slice_len);
        }
        let item_count = molecule::unpack_number(slice) as usize;
        if item_count == 0 {
            if slice_len != molecule::NUMBER_SIZE {
                return ve!(Self, TotalSizeNotMatch, molecule::NUMBER_SIZE, slice_len);
            }
            return Ok(());
        }
        let total_size = molecule::NUMBER_SIZE + Self::ITEM_SIZE * item_count;
        if slice_len != total_size {
            return ve!(Self, TotalSizeNotMatch, total_size, slice_len);
        }
        Ok(())
    }
}
#[derive(Debug, Default)]
pub struct CompactNFTIdVecBuilder(pub(crate) Vec<CompactNFTId>);
impl CompactNFTIdVecBuilder {
    pub const ITEM_SIZE: usize = 29;

    pub fn set(mut self, v: Vec<CompactNFTId>) -> Self {
        self.0 = v;
        self
    }

    pub fn push(mut self, v: CompactNFTId) -> Self {
        self.0.push(v);
        self
    }

    pub fn extend<T: ::core::iter::IntoIterator<Item = CompactNFTId>>(mut self, iter: T) -> Self {
        for elem in iter {
            self.0.push(elem);
        }
        self
    }
}
impl molecule::prelude::Builder for CompactNFTIdVecBuilder {
    type Entity = CompactNFTIdVec;

    const NAME: &'static str = "CompactNFTIdVecBuilder";

    fn expected_length(&self) -> usize {
        molecule::NUMBER_SIZE + Self::ITEM_SIZE * self.0.len()
    }

    fn write<W: molecule::io::Write>(&self, writer: &mut W) -> molecule::io::Result<()> {
        writer.write_all(&molecule::pack_number(self.0.len() as molecule::Number))?;
        for inner in &self.0[..] {
            writer.write_all(inner.as_slice())?;
        }
        Ok(())
    }

    fn build(&self) -> Self::Entity {
        let mut inner = Vec::with_capacity(self.expected_length());
        self.write(&mut inner)
            .unwrap_or_else(|_| panic!("{} build should be ok", Self::NAME));
        CompactNFTIdVec::new_unchecked(inner.into())
    }
}
pub struct CompactNFTIdVecIterator(CompactNFTIdVec, usize, usize);
impl ::core::iter::Iterator for CompactNFTIdVecIterator {
    type Item = CompactNFTId;

    fn next(&mut self) -> Option<Self::Item> {
        if self.1 >= self.2 {
            None
        } else {
            let ret = self.0.get_unchecked(self.1);
            self.1 += 1;
            Some(ret)
        }
    }
}
impl ::core::iter::ExactSizeIterator for CompactNFTIdVecIterator {
    fn len(&self) -> usize {
        self.2 - self.1
    }
}
impl ::core::iter::IntoIterator for CompactNFTIdVec {
    type IntoIter = CompactNFTIdVecIterator;
    type Item = CompactNFTId;

    fn into_iter(self) -> Self::IntoIter {
        let len = self.len();
        CompactNFTIdVecIterator(self, 0, len)
    }
}
impl<'r> CompactNFTIdVecReader<'r> {
    pub fn iter<'t>(&'t self) -> CompactNFTIdVecReaderIterator<'t, 'r> {
        CompactNFTIdVecReaderIterator(&self, 0, self.len())
    }
}
pub struct CompactNFTIdVecReaderIterator<'t, 'r>(&'t CompactNFTIdVecReader<'r>, usize, usize);
impl<'t: 'r, 'r> ::core::iter::Iterator for CompactNFTIdVecReaderIterator<'t, 'r> {
    type Item = CompactNFTIdReader<'t>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.1 >= self.2 {
            None
        } else {
            let ret = self.0.get_unchecked(self.1);
            self.1 += 1;
            Some(ret)
        }
    }
}
impl<'t: 'r, 'r> ::core::iter::ExactSizeIterator for CompactNFTIdVecReaderIterator<'t, 'r> {
    fn len(&self) -> usize {
        self.2 - self.1
    }
}
#[derive(Clone)]
pub struct CompactNFTInfo(molecule::bytes::Bytes);
impl ::core::fmt::LowerHex for CompactNFTInfo {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl ::core::fmt::Debug for CompactNFTInfo {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl ::core::fmt::Display for CompactNFTInfo {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(f, "{}: {}", "characteristic", self.characteristic())?;
        write!(f, ", {}: {}", "configure", self.configure())?;
        write!(f, ", {}: {}", "state", self.state())?;
        write!(f, " }}")
    }
}
impl ::core::default::Default for CompactNFTInfo {
    fn default() -> Self {
        let v: Vec<u8> = vec![0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
        CompactNFTInfo::new_unchecked(v.into())
    }
}
impl CompactNFTInfo {
    pub const FIELD_COUNT: usize = 3;
    pub const FIELD_SIZES: [usize; 3] = [8, 1, 1];
    pub const TOTAL_SIZE: usize = 10;

    pub fn characteristic(&self) -> Characteristic {
        Characteristic::new_unchecked(self.0.slice(0..8))
    }

    pub fn configure(&self) -> Byte {
        Byte::new_unchecked(self.0.slice(8..9))
    }

    pub fn state(&self) -> Byte {
        Byte::new_unchecked(self.0.slice(9..10))
    }

    pub fn as_reader<'r>(&'r self) -> CompactNFTInfoReader<'r> {
        CompactNFTInfoReader::new_unchecked(self.as_slice())
    }
}
impl molecule::prelude::Entity for CompactNFTInfo {
    type Builder = CompactNFTInfoBuilder;

    const NAME: &'static str = "CompactNFTInfo";

    fn new_unchecked(data: molecule::bytes::Bytes) -> Self {
        CompactNFTInfo(data)
    }

    fn as_bytes(&self) -> molecule::bytes::Bytes {
        self.0.clone()
    }

    fn as_slice(&self) -> &[u8] {
        &self.0[..]
    }

    fn from_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        CompactNFTInfoReader::from_slice(slice).map(|reader| reader.to_entity())
    }

    fn from_compatible_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        CompactNFTInfoReader::from_compatible_slice(slice).map(|reader| reader.to_entity())
    }

    fn new_builder() -> Self::Builder {
        ::core::default::Default::default()
    }

    fn as_builder(self) -> Self::Builder {
        Self::new_builder()
            .characteristic(self.characteristic())
            .configure(self.configure())
            .state(self.state())
    }
}
#[derive(Clone, Copy)]
pub struct CompactNFTInfoReader<'r>(&'r [u8]);
impl<'r> ::core::fmt::LowerHex for CompactNFTInfoReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl<'r> ::core::fmt::Debug for CompactNFTInfoReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl<'r> ::core::fmt::Display for CompactNFTInfoReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(f, "{}: {}", "characteristic", self.characteristic())?;
        write!(f, ", {}: {}", "configure", self.configure())?;
        write!(f, ", {}: {}", "state", self.state())?;
        write!(f, " }}")
    }
}
impl<'r> CompactNFTInfoReader<'r> {
    pub const FIELD_COUNT: usize = 3;
    pub const FIELD_SIZES: [usize; 3] = [8, 1, 1];
    pub const TOTAL_SIZE: usize = 10;

    pub fn characteristic(&self) -> CharacteristicReader<'r> {
        CharacteristicReader::new_unchecked(&self.as_slice()[0..8])
    }

    pub fn configure(&self) -> ByteReader<'r> {
        ByteReader::new_unchecked(&self.as_slice()[8..9])
    }

    pub fn state(&self) -> ByteReader<'r> {
        ByteReader::new_unchecked(&self.as_slice()[9..10])
    }
}
impl<'r> molecule::prelude::Reader<'r> for CompactNFTInfoReader<'r> {
    type Entity = CompactNFTInfo;

    const NAME: &'static str = "CompactNFTInfoReader";

    fn to_entity(&self) -> Self::Entity {
        Self::Entity::new_unchecked(self.as_slice().to_owned().into())
    }

    fn new_unchecked(slice: &'r [u8]) -> Self {
        CompactNFTInfoReader(slice)
    }

    fn as_slice(&self) -> &'r [u8] {
        self.0
    }

    fn verify(slice: &[u8], _compatible: bool) -> molecule::error::VerificationResult<()> {
        use molecule::verification_error as ve;
        let slice_len = slice.len();
        if slice_len != Self::TOTAL_SIZE {
            return ve!(Self, TotalSizeNotMatch, Self::TOTAL_SIZE, slice_len);
        }
        Ok(())
    }
}
#[derive(Debug, Default)]
pub struct CompactNFTInfoBuilder {
    pub(crate) characteristic: Characteristic,
    pub(crate) configure:      Byte,
    pub(crate) state:          Byte,
}
impl CompactNFTInfoBuilder {
    pub const FIELD_COUNT: usize = 3;
    pub const FIELD_SIZES: [usize; 3] = [8, 1, 1];
    pub const TOTAL_SIZE: usize = 10;

    pub fn characteristic(mut self, v: Characteristic) -> Self {
        self.characteristic = v;
        self
    }

    pub fn configure(mut self, v: Byte) -> Self {
        self.configure = v;
        self
    }

    pub fn state(mut self, v: Byte) -> Self {
        self.state = v;
        self
    }
}
impl molecule::prelude::Builder for CompactNFTInfoBuilder {
    type Entity = CompactNFTInfo;

    const NAME: &'static str = "CompactNFTInfoBuilder";

    fn expected_length(&self) -> usize {
        Self::TOTAL_SIZE
    }

    fn write<W: molecule::io::Write>(&self, writer: &mut W) -> molecule::io::Result<()> {
        writer.write_all(self.characteristic.as_slice())?;
        writer.write_all(self.configure.as_slice())?;
        writer.write_all(self.state.as_slice())?;
        Ok(())
    }

    fn build(&self) -> Self::Entity {
        let mut inner = Vec::with_capacity(self.expected_length());
        self.write(&mut inner)
            .unwrap_or_else(|_| panic!("{} build should be ok", Self::NAME));
        CompactNFTInfo::new_unchecked(inner.into())
    }
}
#[derive(Clone)]
pub struct CompactNFTInfoVec(molecule::bytes::Bytes);
impl ::core::fmt::LowerHex for CompactNFTInfoVec {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl ::core::fmt::Debug for CompactNFTInfoVec {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl ::core::fmt::Display for CompactNFTInfoVec {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} [", Self::NAME)?;
        for i in 0..self.len() {
            if i == 0 {
                write!(f, "{}", self.get_unchecked(i))?;
            } else {
                write!(f, ", {}", self.get_unchecked(i))?;
            }
        }
        write!(f, "]")
    }
}
impl ::core::default::Default for CompactNFTInfoVec {
    fn default() -> Self {
        let v: Vec<u8> = vec![0, 0, 0, 0];
        CompactNFTInfoVec::new_unchecked(v.into())
    }
}
impl CompactNFTInfoVec {
    pub const ITEM_SIZE: usize = 10;

    pub fn total_size(&self) -> usize {
        molecule::NUMBER_SIZE * (self.item_count() + 1)
    }

    pub fn item_count(&self) -> usize {
        molecule::unpack_number(self.as_slice()) as usize
    }

    pub fn len(&self) -> usize {
        self.item_count()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    pub fn get(&self, idx: usize) -> Option<CompactNFTInfo> {
        if idx >= self.len() {
            None
        } else {
            Some(self.get_unchecked(idx))
        }
    }

    pub fn get_unchecked(&self, idx: usize) -> CompactNFTInfo {
        let start = molecule::NUMBER_SIZE + Self::ITEM_SIZE * idx;
        let end = start + Self::ITEM_SIZE;
        CompactNFTInfo::new_unchecked(self.0.slice(start..end))
    }

    pub fn as_reader<'r>(&'r self) -> CompactNFTInfoVecReader<'r> {
        CompactNFTInfoVecReader::new_unchecked(self.as_slice())
    }
}
impl molecule::prelude::Entity for CompactNFTInfoVec {
    type Builder = CompactNFTInfoVecBuilder;

    const NAME: &'static str = "CompactNFTInfoVec";

    fn new_unchecked(data: molecule::bytes::Bytes) -> Self {
        CompactNFTInfoVec(data)
    }

    fn as_bytes(&self) -> molecule::bytes::Bytes {
        self.0.clone()
    }

    fn as_slice(&self) -> &[u8] {
        &self.0[..]
    }

    fn from_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        CompactNFTInfoVecReader::from_slice(slice).map(|reader| reader.to_entity())
    }

    fn from_compatible_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        CompactNFTInfoVecReader::from_compatible_slice(slice).map(|reader| reader.to_entity())
    }

    fn new_builder() -> Self::Builder {
        ::core::default::Default::default()
    }

    fn as_builder(self) -> Self::Builder {
        Self::new_builder().extend(self.into_iter())
    }
}
#[derive(Clone, Copy)]
pub struct CompactNFTInfoVecReader<'r>(&'r [u8]);
impl<'r> ::core::fmt::LowerHex for CompactNFTInfoVecReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl<'r> ::core::fmt::Debug for CompactNFTInfoVecReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl<'r> ::core::fmt::Display for CompactNFTInfoVecReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} [", Self::NAME)?;
        for i in 0..self.len() {
            if i == 0 {
                write!(f, "{}", self.get_unchecked(i))?;
            } else {
                write!(f, ", {}", self.get_unchecked(i))?;
            }
        }
        write!(f, "]")
    }
}
impl<'r> CompactNFTInfoVecReader<'r> {
    pub const ITEM_SIZE: usize = 10;

    pub fn total_size(&self) -> usize {
        molecule::NUMBER_SIZE * (self.item_count() + 1)
    }

    pub fn item_count(&self) -> usize {
        molecule::unpack_number(self.as_slice()) as usize
    }

    pub fn len(&self) -> usize {
        self.item_count()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    pub fn get(&self, idx: usize) -> Option<CompactNFTInfoReader<'r>> {
        if idx >= self.len() {
            None
        } else {
            Some(self.get_unchecked(idx))
        }
    }

    pub fn get_unchecked(&self, idx: usize) -> CompactNFTInfoReader<'r> {
        let start = molecule::NUMBER_SIZE + Self::ITEM_SIZE * idx;
        let end = start + Self::ITEM_SIZE;
        CompactNFTInfoReader::new_unchecked(&self.as_slice()[start..end])
    }
}
impl<'r> molecule::prelude::Reader<'r> for CompactNFTInfoVecReader<'r> {
    type Entity = CompactNFTInfoVec;

    const NAME: &'static str = "CompactNFTInfoVecReader";

    fn to_entity(&self) -> Self::Entity {
        Self::Entity::new_unchecked(self.as_slice().to_owned().into())
    }

    fn new_unchecked(slice: &'r [u8]) -> Self {
        CompactNFTInfoVecReader(slice)
    }

    fn as_slice(&self) -> &'r [u8] {
        self.0
    }

    fn verify(slice: &[u8], _compatible: bool) -> molecule::error::VerificationResult<()> {
        use molecule::verification_error as ve;
        let slice_len = slice.len();
        if slice_len < molecule::NUMBER_SIZE {
            return ve!(Self, HeaderIsBroken, molecule::NUMBER_SIZE, slice_len);
        }
        let item_count = molecule::unpack_number(slice) as usize;
        if item_count == 0 {
            if slice_len != molecule::NUMBER_SIZE {
                return ve!(Self, TotalSizeNotMatch, molecule::NUMBER_SIZE, slice_len);
            }
            return Ok(());
        }
        let total_size = molecule::NUMBER_SIZE + Self::ITEM_SIZE * item_count;
        if slice_len != total_size {
            return ve!(Self, TotalSizeNotMatch, total_size, slice_len);
        }
        Ok(())
    }
}
#[derive(Debug, Default)]
pub struct CompactNFTInfoVecBuilder(pub(crate) Vec<CompactNFTInfo>);
impl CompactNFTInfoVecBuilder {
    pub const ITEM_SIZE: usize = 10;

    pub fn set(mut self, v: Vec<CompactNFTInfo>) -> Self {
        self.0 = v;
        self
    }

    pub fn push(mut self, v: CompactNFTInfo) -> Self {
        self.0.push(v);
        self
    }

    pub fn extend<T: ::core::iter::IntoIterator<Item = CompactNFTInfo>>(mut self, iter: T) -> Self {
        for elem in iter {
            self.0.push(elem);
        }
        self
    }
}
impl molecule::prelude::Builder for CompactNFTInfoVecBuilder {
    type Entity = CompactNFTInfoVec;

    const NAME: &'static str = "CompactNFTInfoVecBuilder";

    fn expected_length(&self) -> usize {
        molecule::NUMBER_SIZE + Self::ITEM_SIZE * self.0.len()
    }

    fn write<W: molecule::io::Write>(&self, writer: &mut W) -> molecule::io::Result<()> {
        writer.write_all(&molecule::pack_number(self.0.len() as molecule::Number))?;
        for inner in &self.0[..] {
            writer.write_all(inner.as_slice())?;
        }
        Ok(())
    }

    fn build(&self) -> Self::Entity {
        let mut inner = Vec::with_capacity(self.expected_length());
        self.write(&mut inner)
            .unwrap_or_else(|_| panic!("{} build should be ok", Self::NAME));
        CompactNFTInfoVec::new_unchecked(inner.into())
    }
}
pub struct CompactNFTInfoVecIterator(CompactNFTInfoVec, usize, usize);
impl ::core::iter::Iterator for CompactNFTInfoVecIterator {
    type Item = CompactNFTInfo;

    fn next(&mut self) -> Option<Self::Item> {
        if self.1 >= self.2 {
            None
        } else {
            let ret = self.0.get_unchecked(self.1);
            self.1 += 1;
            Some(ret)
        }
    }
}
impl ::core::iter::ExactSizeIterator for CompactNFTInfoVecIterator {
    fn len(&self) -> usize {
        self.2 - self.1
    }
}
impl ::core::iter::IntoIterator for CompactNFTInfoVec {
    type IntoIter = CompactNFTInfoVecIterator;
    type Item = CompactNFTInfo;

    fn into_iter(self) -> Self::IntoIter {
        let len = self.len();
        CompactNFTInfoVecIterator(self, 0, len)
    }
}
impl<'r> CompactNFTInfoVecReader<'r> {
    pub fn iter<'t>(&'t self) -> CompactNFTInfoVecReaderIterator<'t, 'r> {
        CompactNFTInfoVecReaderIterator(&self, 0, self.len())
    }
}
pub struct CompactNFTInfoVecReaderIterator<'t, 'r>(&'t CompactNFTInfoVecReader<'r>, usize, usize);
impl<'t: 'r, 'r> ::core::iter::Iterator for CompactNFTInfoVecReaderIterator<'t, 'r> {
    type Item = CompactNFTInfoReader<'t>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.1 >= self.2 {
            None
        } else {
            let ret = self.0.get_unchecked(self.1);
            self.1 += 1;
            Some(ret)
        }
    }
}
impl<'t: 'r, 'r> ::core::iter::ExactSizeIterator for CompactNFTInfoVecReaderIterator<'t, 'r> {
    fn len(&self) -> usize {
        self.2 - self.1
    }
}
#[derive(Clone)]
pub struct UpdateCompactNFTEntries(molecule::bytes::Bytes);
impl ::core::fmt::LowerHex for UpdateCompactNFTEntries {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl ::core::fmt::Debug for UpdateCompactNFTEntries {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl ::core::fmt::Display for UpdateCompactNFTEntries {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(f, "{}: {}", "nft_ids", self.nft_ids())?;
        write!(f, ", {}: {}", "nft_infos", self.nft_infos())?;
        write!(f, ", {}: {}", "kv_proof", self.kv_proof())?;
        let extra_count = self.count_extra_fields();
        if extra_count != 0 {
            write!(f, ", .. ({} fields)", extra_count)?;
        }
        write!(f, " }}")
    }
}
impl ::core::default::Default for UpdateCompactNFTEntries {
    fn default() -> Self {
        let v: Vec<u8> = vec![
            28, 0, 0, 0, 16, 0, 0, 0, 20, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        ];
        UpdateCompactNFTEntries::new_unchecked(v.into())
    }
}
impl UpdateCompactNFTEntries {
    pub const FIELD_COUNT: usize = 3;

    pub fn total_size(&self) -> usize {
        molecule::unpack_number(self.as_slice()) as usize
    }

    pub fn field_count(&self) -> usize {
        if self.total_size() == molecule::NUMBER_SIZE {
            0
        } else {
            (molecule::unpack_number(&self.as_slice()[molecule::NUMBER_SIZE..]) as usize / 4) - 1
        }
    }

    pub fn count_extra_fields(&self) -> usize {
        self.field_count() - Self::FIELD_COUNT
    }

    pub fn has_extra_fields(&self) -> bool {
        Self::FIELD_COUNT != self.field_count()
    }

    pub fn nft_ids(&self) -> CompactNFTIdVec {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[4..]) as usize;
        let end = molecule::unpack_number(&slice[8..]) as usize;
        CompactNFTIdVec::new_unchecked(self.0.slice(start..end))
    }

    pub fn nft_infos(&self) -> CompactNFTInfoVec {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[8..]) as usize;
        let end = molecule::unpack_number(&slice[12..]) as usize;
        CompactNFTInfoVec::new_unchecked(self.0.slice(start..end))
    }

    pub fn kv_proof(&self) -> Bytes {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[12..]) as usize;
        if self.has_extra_fields() {
            let end = molecule::unpack_number(&slice[16..]) as usize;
            Bytes::new_unchecked(self.0.slice(start..end))
        } else {
            Bytes::new_unchecked(self.0.slice(start..))
        }
    }

    pub fn as_reader<'r>(&'r self) -> UpdateCompactNFTEntriesReader<'r> {
        UpdateCompactNFTEntriesReader::new_unchecked(self.as_slice())
    }
}
impl molecule::prelude::Entity for UpdateCompactNFTEntries {
    type Builder = UpdateCompactNFTEntriesBuilder;

    const NAME: &'static str = "UpdateCompactNFTEntries";

    fn new_unchecked(data: molecule::bytes::Bytes) -> Self {
        UpdateCompactNFTEntries(data)
    }

    fn as_bytes(&self) -> molecule::bytes::Bytes {
        self.0.clone()
    }

    fn as_slice(&self) -> &[u8] {
        &self.0[..]
    }

    fn from_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        UpdateCompactNFTEntriesReader::from_slice(slice).map(|reader| reader.to_entity())
    }

    fn from_compatible_slice(slice: &[u8]) -> molecule::error::VerificationResult<Self> {
        UpdateCompactNFTEntriesReader::from_compatible_slice(slice).map(|reader| reader.to_entity())
    }

    fn new_builder() -> Self::Builder {
        ::core::default::Default::default()
    }

    fn as_builder(self) -> Self::Builder {
        Self::new_builder()
            .nft_ids(self.nft_ids())
            .nft_infos(self.nft_infos())
            .kv_proof(self.kv_proof())
    }
}
#[derive(Clone, Copy)]
pub struct UpdateCompactNFTEntriesReader<'r>(&'r [u8]);
impl<'r> ::core::fmt::LowerHex for UpdateCompactNFTEntriesReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        use molecule::hex_string;
        if f.alternate() {
            write!(f, "0x")?;
        }
        write!(f, "{}", hex_string(self.as_slice()))
    }
}
impl<'r> ::core::fmt::Debug for UpdateCompactNFTEntriesReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{}({:#x})", Self::NAME, self)
    }
}
impl<'r> ::core::fmt::Display for UpdateCompactNFTEntriesReader<'r> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
        write!(f, "{} {{ ", Self::NAME)?;
        write!(f, "{}: {}", "nft_ids", self.nft_ids())?;
        write!(f, ", {}: {}", "nft_infos", self.nft_infos())?;
        write!(f, ", {}: {}", "kv_proof", self.kv_proof())?;
        let extra_count = self.count_extra_fields();
        if extra_count != 0 {
            write!(f, ", .. ({} fields)", extra_count)?;
        }
        write!(f, " }}")
    }
}
impl<'r> UpdateCompactNFTEntriesReader<'r> {
    pub const FIELD_COUNT: usize = 3;

    pub fn total_size(&self) -> usize {
        molecule::unpack_number(self.as_slice()) as usize
    }

    pub fn field_count(&self) -> usize {
        if self.total_size() == molecule::NUMBER_SIZE {
            0
        } else {
            (molecule::unpack_number(&self.as_slice()[molecule::NUMBER_SIZE..]) as usize / 4) - 1
        }
    }

    pub fn count_extra_fields(&self) -> usize {
        self.field_count() - Self::FIELD_COUNT
    }

    pub fn has_extra_fields(&self) -> bool {
        Self::FIELD_COUNT != self.field_count()
    }

    pub fn nft_ids(&self) -> CompactNFTIdVecReader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[4..]) as usize;
        let end = molecule::unpack_number(&slice[8..]) as usize;
        CompactNFTIdVecReader::new_unchecked(&self.as_slice()[start..end])
    }

    pub fn nft_infos(&self) -> CompactNFTInfoVecReader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[8..]) as usize;
        let end = molecule::unpack_number(&slice[12..]) as usize;
        CompactNFTInfoVecReader::new_unchecked(&self.as_slice()[start..end])
    }

    pub fn kv_proof(&self) -> BytesReader<'r> {
        let slice = self.as_slice();
        let start = molecule::unpack_number(&slice[12..]) as usize;
        if self.has_extra_fields() {
            let end = molecule::unpack_number(&slice[16..]) as usize;
            BytesReader::new_unchecked(&self.as_slice()[start..end])
        } else {
            BytesReader::new_unchecked(&self.as_slice()[start..])
        }
    }
}
impl<'r> molecule::prelude::Reader<'r> for UpdateCompactNFTEntriesReader<'r> {
    type Entity = UpdateCompactNFTEntries;

    const NAME: &'static str = "UpdateCompactNFTEntriesReader";

    fn to_entity(&self) -> Self::Entity {
        Self::Entity::new_unchecked(self.as_slice().to_owned().into())
    }

    fn new_unchecked(slice: &'r [u8]) -> Self {
        UpdateCompactNFTEntriesReader(slice)
    }

    fn as_slice(&self) -> &'r [u8] {
        self.0
    }

    fn verify(slice: &[u8], compatible: bool) -> molecule::error::VerificationResult<()> {
        use molecule::verification_error as ve;
        let slice_len = slice.len();
        if slice_len < molecule::NUMBER_SIZE {
            return ve!(Self, HeaderIsBroken, molecule::NUMBER_SIZE, slice_len);
        }
        let total_size = molecule::unpack_number(slice) as usize;
        if slice_len != total_size {
            return ve!(Self, TotalSizeNotMatch, total_size, slice_len);
        }
        if slice_len == molecule::NUMBER_SIZE && Self::FIELD_COUNT == 0 {
            return Ok(());
        }
        if slice_len < molecule::NUMBER_SIZE * 2 {
            return ve!(Self, HeaderIsBroken, molecule::NUMBER_SIZE * 2, slice_len);
        }
        let offset_first = molecule::unpack_number(&slice[molecule::NUMBER_SIZE..]) as usize;
        if offset_first % molecule::NUMBER_SIZE != 0 || offset_first < molecule::NUMBER_SIZE * 2 {
            return ve!(Self, OffsetsNotMatch);
        }
        if slice_len < offset_first {
            return ve!(Self, HeaderIsBroken, offset_first, slice_len);
        }
        let field_count = offset_first / molecule::NUMBER_SIZE - 1;
        if field_count < Self::FIELD_COUNT {
            return ve!(Self, FieldCountNotMatch, Self::FIELD_COUNT, field_count);
        } else if !compatible && field_count > Self::FIELD_COUNT {
            return ve!(Self, FieldCountNotMatch, Self::FIELD_COUNT, field_count);
        };
        let mut offsets: Vec<usize> = slice[molecule::NUMBER_SIZE..offset_first]
            .chunks_exact(molecule::NUMBER_SIZE)
            .map(|x| molecule::unpack_number(x) as usize)
            .collect();
        offsets.push(total_size);
        if offsets.windows(2).any(|i| i[0] > i[1]) {
            return ve!(Self, OffsetsNotMatch);
        }
        CompactNFTIdVecReader::verify(&slice[offsets[0]..offsets[1]], compatible)?;
        CompactNFTInfoVecReader::verify(&slice[offsets[1]..offsets[2]], compatible)?;
        BytesReader::verify(&slice[offsets[2]..offsets[3]], compatible)?;
        Ok(())
    }
}
#[derive(Debug, Default)]
pub struct UpdateCompactNFTEntriesBuilder {
    pub(crate) nft_ids:   CompactNFTIdVec,
    pub(crate) nft_infos: CompactNFTInfoVec,
    pub(crate) kv_proof:  Bytes,
}
impl UpdateCompactNFTEntriesBuilder {
    pub const FIELD_COUNT: usize = 3;

    pub fn nft_ids(mut self, v: CompactNFTIdVec) -> Self {
        self.nft_ids = v;
        self
    }

    pub fn nft_infos(mut self, v: CompactNFTInfoVec) -> Self {
        self.nft_infos = v;
        self
    }

    pub fn kv_proof(mut self, v: Bytes) -> Self {
        self.kv_proof = v;
        self
    }
}
impl molecule::prelude::Builder for UpdateCompactNFTEntriesBuilder {
    type Entity = UpdateCompactNFTEntries;

    const NAME: &'static str = "UpdateCompactNFTEntriesBuilder";

    fn expected_length(&self) -> usize {
        molecule::NUMBER_SIZE * (Self::FIELD_COUNT + 1)
            + self.nft_ids.as_slice().len()
            + self.nft_infos.as_slice().len()
            + self.kv_proof.as_slice().len()
    }

    fn write<W: molecule::io::Write>(&self, writer: &mut W) -> molecule::io::Result<()> {
        let mut total_size = molecule::NUMBER_SIZE * (Self::FIELD_COUNT + 1);
        let mut offsets = Vec::with_capacity(Self::FIELD_COUNT);
        offsets.push(total_size);
        total_size += self.nft_ids.as_slice().len();
        offsets.push(total_size);
        total_size += self.nft_infos.as_slice().len();
        offsets.push(total_size);
        total_size += self.kv_proof.as_slice().len();
        writer.write_all(&molecule::pack_number(total_size as molecule::Number))?;
        for offset in offsets.into_iter() {
            writer.write_all(&molecule::pack_number(offset as molecule::Number))?;
        }
        writer.write_all(self.nft_ids.as_slice())?;
        writer.write_all(self.nft_infos.as_slice())?;
        writer.write_all(self.kv_proof.as_slice())?;
        Ok(())
    }

    fn build(&self) -> Self::Entity {
        let mut inner = Vec::with_capacity(self.expected_length());
        self.write(&mut inner)
            .unwrap_or_else(|_| panic!("{} build should be ok", Self::NAME));
        UpdateCompactNFTEntries::new_unchecked(inner.into())
    }
}
