[workspace]
members = ["issuer-type", "class-type", "nft-type", "script-utils", "compact-registry-type", "compact-nft-type"]

[profile.release]
overflow-checks = true
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'
