[package]
name = "nft-smt"
version = "0.3.0"
edition = "2018"

[dependencies]
ckb-std = "0.7.1"
ckb-types = "0.43.2"
molecule = {version = "0.6", default_features = false, optional = true}


[features]
default = ["std","ckb-types"]
std = []
no-std = ["ckb-std","molecule"]
