name: CI

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-12-25
          override: true

      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: nightly
          docker_nightly_version: snapshot-20201008

      - name: Install Capsule
        env:
          CAPSULE_VERSION: v0.7.3
        run: |
          mkdir -p ./capsule && curl -L https://github.com/nervosnetwork/capsule/releases/download/${CAPSULE_VERSION}/capsule_${CAPSULE_VERSION}_x86_64-linux.tar.gz | tar xvz -C ./capsule --strip-components=1
          chmod +x ./capsule/capsule

      - name: Check Rust format
        run: cargo fmt -- --check

      - name: Build contracts
        run: ./capsule/capsule build

      - name: Test contracts
        run: ./capsule/capsule test
