name: CI

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-09-28
          override: true

      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: nightly
          docker_nightly_version: snapshot-20201008

      - name: Install Capsule
        env:
          CAPSULE_VERSION: v0.4.3
        run: |
          curl -OL https://github.com/nervosnetwork/capsule/releases/download/${CAPSULE_VERSION}/capsule_${CAPSULE_VERSION}_x86_64-linux.tar.gz && tar xf capsule_${CAPSULE_VERSION}_x86_64-linux.tar.gz && echo `pwd`/capsule_${CAPSULE_VERSION}_x86_64-linux >> $GITHUB_PATH

      - name: Check Tests format
          run: cargo fmt -- --check

      - name: Check Rust format
        run: cd contracts && cargo fmt -- --check

      - name: Cargo clippy check
        run: cd contracts && cargo clippy

      - name: Build contracts
        run: make build

      - name: Test contracts
        run: make test
